apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test-pod
    image: tommcgreal11/testimage:latest
    ports:
    - containerPort: 80
    command: ["sh", "-c", "while true; do echo 'Hello, Kubernetes!'; sleep 3600; done"]
